### ISSUE TITLE
It doesn't work for internal domains

### ISSUE THREAD

**Issue by fvlaicu** [containous/acme-fixer#1]
https://github.com/containous/acme-fixer/blob/e1503e7fab93691d116ddbecf49226bd20527fca/check/check.go#L21
Because the dns resolver is hardcoded, it won't work with local domains and internal CAs.

**Comment by ldez** [comment]
This tool has created only to handle the following problem https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591

So I don't understand your issue.

**Comment by fvlaicu** [comment]
For some reason, I thought it would delete expired certs, so that it forces traefik to generate requests for brand new certs, instead of renewals.
